<?php if($this->getAmbiente() != "test"): ?>
<script src="https://devteam.com.ar/hibrido2.js"></script>
<?php else: ?>
<script src="https://devteam.com.ar/hibrido2.js"></script>
<?php endif; ?>

<div class="contentContainer main" style="width: auto">
<div class="alert alert-warning">
		<h4>Advertencia:</h4>
		<ol id="alert-form">
		</ol>
	</div>

	<div id="tp-form-tph">
		<div id="tp-logo"></div>
		<div id="tp-content-form">

			<h5>Eleg&iacute; tu forma de pago </h5>
			
			<div class="">
				<select id="formaPagoCbx" class="select-control"></select>
			</div>	

			<div class="input-group input-group-sm cienper">
				<label id="numeroTarjetaLbl"></label><div></div>
				<input id="numeroTarjetaTxt" class="form-control">
			</div>


			<label id="fechaLbl" class="left"></label>
			<div class="">
				<select id="mesCbx" class="select-control"></select>
			</div>	

			<div class="">
				<select id="anioCbx" class="select-control"></select>
			</div>				


			<div class="">
				<select id="medioPagoCbx" class="select-control"></select>
			</div>			


			<div class="">
				<select id="bancoCbx" class="select-control"></select>
			</div>	
			
			<div class="">
				<select id="promosCbx" class="select-control"></select>
				<label id="promosLbl"></label>
			</div>

			<div class="">
			    <!-- Para los casos en el que el comercio opera con PEI -->
			    <label id="peiLbl"></label>
			    <input id="peiCbx" class="select-control"/>
			</div>
			

			
		
			<div class="input-group input-group-sm cincuentaper">
				<input id="codigoSeguridadTxt" class="form-control"/>
				<label id="codigoSeguridadLbl" class="tp-label"></label>
			</div>
			
			<div class="input-group input-group-sm cincuentaper">
				<input id="nombreTxt" class="form-control"/>
			</div>
			
			<div>
				<select id="tipoDocCbx" class="select-control cincuentaper"></select>
			</div>
			
			<div class="input-group input-group-sm cincuentaper">
				<input id="nroDocTxt" class="form-control"/>
			</div>
			
			<div class="input-group input-group-sm cincuentaper">
				<input id="emailTxt" class="form-control" /><br/>
			</div>



			
			<div class="input-group input-group-sm">
			    <!-- Para los casos en el que el comercio opera con PEI -->
			    <label id="tokenPeiLbl"></label>
			    <input class="form-control" id="tokenPeiTxt"/>
			</div>
			<div id="tp-bt-wrapper">
				<button id="btnPagoBilletera" class="tp-button button btn-sm btn btn-success">Pagar con Billetera</button>
				<button id="MY_btnConfirmarPago" style="display: none!important"/>
				<button id="btnConfirmarPagoValida" class="tp-button button btn-sm btn btn-success">Pagar</button>
			</div>
		</div>	
	</div>

	</div>

	<script>

			jQuery("#formaDePagoCbx").change(function () {
				if(this.value == 500 || this.value == 501){
					jQuery(".spacer").hide();
				}else{
					jQuery(".spacer").show();
				}
			});
			jQuery(".alert").hide();
			
			jQuery("#btnConfirmarPagoValida").on("click", function(){
				jQuery('#alert-form').empty();
				jQuery('.alert-warning').hide();
				jQuery('#MY_btnConfirmarPago').click();
			});

		
		var security = "<?php echo $this->getRequestKey(); ?>";
		//merchandID
		var merchantId = "<?php echo $this->getMerchant(); ?>";
		//monto del pago
		var numericAmount = "<?php echo $this->getAmount(); ?>";
		var mail = "<?php echo $this->getMail(); ?>";
		var CompleteName = "<?php echo $this->getNombre(); ?>";
		

		/************* CONFIGURACION DEL API ************************/
		window.TPFORMAPI.hybridForm.initForm({
			callbackValidationErrorFunction: 'validationCollector',
               botonPagarConBilleteraId: 'btnPagoBilletera',
               callbackBilleteraFunction: 'billeteraPaymentResponse',
			callbackCustomSuccessFunction: 'customPaymentSuccessResponse',
			callbackCustomErrorFunction: 'customPaymentErrorResponse',
			botonPagarId: 'btnConfirmarPagoValida',
			modalCssClass: 'modal-class',
			modalContentCssClass: 'modal-content',
			beforeRequest: 'initLoading',
			afterRequest: 'stopLoading'			
		});
		
		window.TPFORMAPI.hybridForm.setItem({
			publicKey: security,
			merchantId: merchantId,
			defaultNombreApellido: CompleteName,
			defaultMail: mail,
			defaultNumeroDoc: '',
			defaultTipoDoc: 'DNI'
		});

		function validationCollector(parametros) {
			var errorMessage = "<li>"+parametros.error+"</li>";
			jQuery(".alert").show();	
			jQuery("#alert-form").append(errorMessage);	
			console.log(parametros.field + " ==> " + parametros.error);
		}
		function billeteraPaymentResponse(response) {
			if(response.AuthorizationKey)
				window.top.location = "<?php echo $block->getBaseUrl().'todopago/payment/secondstep/id/'.$this->getOrden(); ?>?Answer="+response.AuthorizationKey;
			else
				window.top.location = "<?php echo $block->getBaseUrl().'todopago/payment/secondstep/id/'.$this->getOrden(); ?>?error="+response.ResultMessage;
		}
		function customPaymentSuccessResponse(response) {
			window.top.location = "<?php echo $block->getBaseUrl().'todopago/payment/secondstep/id/'.$this->getOrden(); ?>?Answer="+response.AuthorizationKey;
		}
		function customPaymentErrorResponse(response) {
			if(response.AuthorizationKey)
				window.top.location = "<?php echo $block->getBaseUrl().'todopago/payment/secondstep/id/'.$this->getOrden(); ?>?Answer="+response.AuthorizationKey;
			else
				window.top.location = "<?php echo $block->getBaseUrl().'todopago/payment/secondstep/id/'.$this->getOrden(); ?>?error="+response.ResultMessage;
		}
		function initLoading() {
			console.log('Cargando');
		}
		function stopLoading() {
			console.log('Stop loading...');
		}

</script>
