<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @see \Magento\Paypal\Block\Adminhtml\System\Config\ApiWizard
 * @var \Magento\Paypal\Block\Adminhtml\System\Config\ApiWizard $block
 */

?>
<div id="tp_configuracion_version_actualiza" style="display: none">
     <p>
          Se encuentra disponible una versi&oacute;n m&aacute;s reciente del plugin de Todo Pago, puede consultarla desde <a href="https://github.com/TodoPago/Plugin-Magento2" target="_blank">aqu&iacute;</a>

     </p>
</div>


<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){     
          versionCompare = function(left, right) {
               if (typeof left + typeof right != "stringstring")
                    return false;
                    
               var a = left.split(".")
               ,   b = right.split(".")
               ,   i = 0, len = Math.max(a.length, b.length);
                        
               for (; i < len; i++) {
                    if ((a[i] && !b[i] && parseInt(a[i]) > 0) || (parseInt(a[i]) > parseInt(b[i]))) {
                         return 1;
                    } else if ((b[i] && !a[i] && parseInt(b[i]) > 0) || (parseInt(a[i]) < parseInt(b[i]))) {
                         return -1;
                    }
               }
                    
               return 0;
          }


          var versionActual='<?php echo $block->getVersionInstalada(); ?>';
          //var versionActual='1.0.0'; //Testing
          versionActual=versionActual.replace(/[^0-9.]/g, '');
          console.log('actual: '+versionActual);

          var versionProd='<?php echo $block->buscarGithub(); ?>';
          console.log('versionprod es = '+versionProd);

          if(versionProd==''){
            console.log('versionProd es null');
              jQuery('#tp_configuracion_version_actualiza').html('<p>Hubo un inconveniente al consultar la API de Github, por favor intente más tarde</p>');
              jQuery('#tp_configuracion_version_actualiza').append();
              jQuery('#tp_configuracion_version_actualiza').show();
          }else{          
            versionProd=versionProd.replace(/[^0-9.]/g, '');
            console.log('en api: '+versionProd);

            if(versionCompare(versionProd, versionActual)>0 && versionProd){
                  console.log('Tiene una version vieja instalada');
                  jQuery('#tp_configuracion_version_actualiza').show();
            }
          }
    });

</script>
