<div class="entry-edit">
	<div class="entry-edit-head">
		<h4>Consulta de estado online</h4>
	</div>
	<div class="fieldset fieldset-wide">
		
		<h5>Estado de la operaci&oacute;n</h5>
		<table>
		<?php 
			$status = $this->getStatus();
			if(isset($status['Operations'])&&is_array($status['Operations'])) {
				echo printGetStatus($status['Operations']);
			} else {
				echo "<tr><td>Sin datos</td><td></td></tr>";
			}

			function printGetStatus($arrayResult, $indent = 0) {
		    	$rta = '';
		    	foreach ($arrayResult as $key => $value) {
		    	    if ($key !== 'nil' && $key !== "@attributes") {
		    			if (is_array($value) ){
		    			    $rta .= "<tr>";
		    			    $rta .= "<td>".str_repeat("-", $indent) . "<strong>$key:</strong></td>";
		    			    $rta .= "<td>".printGetStatus($value, $indent + 2)."</td>";
		    			    $rta .= "</tr>";
		    			} else {
		    			    $rta .= "<tr><td>".str_repeat("-", $indent) . "<strong>$key:</strong></td><td> $value </td></tr>";
		    			}
		    	    }
		    	}
		    	return $rta;
		    }

		?>
		</table>
	</div>
	
</div>
