<div class="entry-edit">
	<div class="entry-edit-head">
		<h4>Consulta de estado online</h4>
	</div>
	<div class="fieldset fieldset-wide">
		
		<h5>Estado de la operaci&oacute;n</h5>
		<table>
		<?php 
			$status = $this->getStatus();
			if(isset($status['Operations'])&&is_array($status['Operations'])) {
				foreach ($status['Operations'] as $key => $value) {
					if($key == "REFUNDS") {
						echo "<tr><td colspan='2'><strong>Devoluciones</strong></td></tr>";
						if(is_array($value) && isset($value["REFUND"])) {
							$value = $value["REFUND"];
							foreach($value as $val) {
								foreach($val as $key => $v) {
									echo "<tr><td><strong>$key: </strong></td><td>".$v."</td></tr>";
								}
								echo "<tr><td colspan='2'>-----------</td></tr>";
							}
						} else {
							echo "<tr><td colspan='2'>Ninguna</td></tr>";
							echo "<tr><td colspan='2'>-----------</td></tr>";
						}
					} else if(is_array($value)) {
						echo "<tr><td><strong>$key: </strong></td><td>".implode(" - ",$value)."</td></tr>";
					} else {
						echo "<tr><td><strong>$key: </strong></td><td>".$value."</td></tr>";	
					}
				}
			} else {
				echo "<tr><td>Sin datos</td><td></td></tr>";
			}
		?>
		</table>
	</div>
	
</div>
